### ISSUE TITLE
Databases.cfg problems

### ISSUE THREAD

**Issue by Pyromachine22** [Impact123/CallAdmin#12]
Hi, i have team fortress 2 serveur and i make a bot to call all admins in the steam group, all work correctly but when i call, my bot is still sleeping, i'm not sure what i'm supposed to write in "database.cfg" file, thanks for help me.

**Comment by Impact123** [comment]
This is explained in [the documentation of the mysql module](https://github.com/Impact123/CallAdmin/wiki/Mysqlmodule-Installation). Please ask for support in [the forum thread](https://forums.alliedmods.net/showthread.php?t=213670) next time, this is only to report bugs and issues. Thanks.
