### ISSUE TITLE
Failed opening required 'include/feedwriter\item.php'

### ISSUE THREAD

**Issue by winniethepoohbear** [Impact123/CallAdmin#14]
```
require_once(): Failed opening required 'include/feedwriter\item.php' (include_path='.:/usr/share/pear:/usr/share/php') in .../calladmin/autoload.php on line 28
```

I've been getting this on the rss.php whenver a new calladmin comes in.
I haven't dug too much to see where the includes path is funky or where nested requires loading is being problematic.

**Comment by winniethepoohbear** [comment]
I forgot to mention, this is the development branch.

**Comment by Impact123** [comment]
I can't reproduce this with the current development code. [There was an error a few days ago](https://github.com/Impact123/CallAdmin/commit/99ffc902329c3e5cf1f8fc39574e12c399411721) which was fixed, do you have the latest code?

**Comment by winniethepoohbear** [comment]
yes, I have the latest.
Are you testing in Windows by chance? (Guessing by the mismatched slashes?)

This is on a centos 7 with latest PHP. I'll have to confirm the last
version later. The character casing in paths in Linux matters so I think
forcing it lowercase in autoloader.php might be bad.

I can't reproduce this with the current development code. There was an
error a few days ago
<https://github.com/Impact123/CallAdmin/commit/99ffc902329c3e5cf1f8fc39574e12c399411721>
which was fixed, do you have the latest code?

—
Reply to this email directly or view it on GitHub
<https://github.com/Impact123/CallAdmin/issues/14#issuecomment-120596023>.

**Comment by Impact123** [comment]
Well, that's embarrassing. [I fixed a similar bug a few days ago](https://github.com/Impact123/CallAdmin/commit/99ffc902329c3e5cf1f8fc39574e12c399411721), but it seems like [i missed something](https://github.com/Impact123/CallAdmin/commit/3f74eaf6fe52437528c970d4b660a7b9ef7a1a1e). I guess that's what you get for not testing on linux too.
