### ISSUE TITLE
[CallAdmin: Mysql module] ConErr: [2002]: Can not connect to local MySQL server through socket '/tmp/mysql.sock' (2)

### ISSUE THREAD

**Issue by SHAREN** [Impact123/CallAdmin#15]
In the logs there is such an error
[CallAdmin: Mysql module] ConErr: [2002]: Can not connect to local MySQL server through socket '/tmp/mysql.sock' (2)
Looked Variables in phpmyadmin: socket = /var/run/mysqld/mysqld.sock , but I have no right to change these values on my hosting. Maybe once, you can change the path to mysql.sock?

The comments are advised to do so:
https://forums.alliedmods.net/showthread.php?p=2261276&highlight=/tmp/mysql.sock#post2261276
and
https://forums.alliedmods.net/showthread.php?p=2065223&highlight=%2Ftmp%2Fmysql.sock#post2065223

**Comment by popoklopsi** [comment]
You just have to google it:

http://stackoverflow.com/questions/16325607/cant-connect-to-local-mysql-server-through-socket-tmp-mysql-sock

**Comment by popoklopsi** [comment]
We can't change that path. 
Try to contact your host, if you do not have the rights to change it.

**Comment by SHAREN** [comment]
Sorry, the error was on my part, support helped me
