### ISSUE TITLE
Steam Guard - Disable

### ISSUE THREAD

**Issue by spot88** [Impact123/CallAdmin#16]
Sorry, some kind of error has occurred: To post this comment, your account must have Steam Guard enabled.

**Comment by Impact123** [comment]
I'm sorry but we can't work with that. Please give us more information.

**Comment by spot88** [comment]
In your guide you tell us to disable steam guard. But when i try to comment in a group, it tells me that i need it enabled. =)

**Comment by Impact123** [comment]
You're not supposed to use the bot account yourself.

**Comment by spot88** [comment]
I know, but i assume when i try to comment, the same will apply for the bot.

**Comment by Impact123** [comment]
The bot doesn't comment in groups though, it only sends messages to friends.

**Comment by spot88** [comment]
aha, it can't update in a group?

**Comment by Impact123** [comment]
No.

**Comment by spot88** [comment]
So it will message everyone it has on friends list?

**Comment by Impact123** [comment]
Everyone that matches the steamid/communityid inside the config file and/or is a member of one of the groups you've set up.

**Comment by spot88** [comment]
Okay thanks, im trying to get this to work now. But i get this Error when i start srcds.exe
" MSVCR120.dll is missing".

**Comment by spot88** [comment]
Failed CallAdmin Steam module.

**Comment by Impact123** [comment]
Try to install [this](https://www.microsoft.com/en-us/download/details.aspx?id=40784) and/or search the web for the error, it's nothing specific to CallAdmin. I'll close this for now because it's not a bug. Feel free to ask if you have further questions.
