### ISSUE TITLE
Translation calladmin_steam

### ISSUE THREAD

**Issue by SHAREN** [Impact123/CallAdmin#17]
https://github.com/Impact123/CallAdmin/blob/development/gameserver/calladmin_steam.sp#L481

If I replace text on rusian on 481 line, server crashing

for example
"\nНовая жалоба на сервере: %s (%s:%d)\nID жалобы: %d\nЖалуется: %s (%s)\nНа игрока: %s (%s)\nПричина: %s\nПрисоединиться: steam://connect/%s:%d\nВойдя на сервер напишите !calladmin_handle %d или /calladmin_handle %d в чат чтобы закрыть жалобу"

**Comment by Impact123** [comment]
Please provide more information, especially about the crash like a crash dump, error log, screen log, debug log, etc.

**Comment by SHAREN** [comment]
Format(sMessage, sizeof(sMessage), "%s жалуется на %s. \"%s\". (%s)\n%s жалуется на %s\nsteam://connect/%s:%d\nПиши в чат !calladmin_handle %d или /calladmin_handle %d чтобы закрыть эту жалобу", sClientName, sTargetName, reason, sServerName, sClientID, sTargetID, sServerIP, serverPort, g_iLastReportID, g_iLastReportID);

Sorry, tested for a long time are now tested is working properly.
