### ISSUE TITLE
Little sourcebans support ( sb_admins.cfg instead of calladmin_steam_steamidlist.cfg)

### ISSUE THREAD

**Issue by SHAREN** [Impact123/CallAdmin#18]
Because then when you add the administrator to SourceBans have to re-add to calladmin_steam_steamidlist
or simply forget to add or remove

file location /addons/sourcemod/configs/sourcebans/sb_admins.cfg
sb_admins.cfg example

```
"Admins"
{
    "nickname"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:1:53533556"
        "group"     "Admins"
    }
    "nickname2"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:0:443849190"
        "group"     "Admins"
    }
    "nickname3"
    {
        "auth"      "steam"
        "identity"      "STEAM_1:1:53479065"
        "group"     "Admins"
    }
}
```
I think that most servers use SourceBans

**Comment by Impact123** [comment]
I remember working with with key values as being painful. Is there a reason why you're not using the steam groups feature for this?
How would we define which admins from the file are "real" admins?

**Comment by SHAREN** [comment]
All existing admins, I add in Sourcebans, for me personally, it will be easier

the second variant it would be nice if the admins were taken from the database
```
"Sourcebans"
{
    "Driver" "default"
    "Host" "11.22.33.44"
    "Database" "database"
    "User" "user"
    "Pass" "pass"
    "Port", "3306"
}
```
I do not know better, but it will be easier installation and use.
If it is difficult to realize if I understand you.

**Comment by Impact123** [comment]
We can't just grab all admins from that file and add them as clients, it has to be configurable somehow.

**Comment by SHAREN** [comment]
maybe you're right about the group Steam.

Only problem with that is that a bot can add as friends it has a low level,  it is necessary to wait until the bot admins will submit an application to friends.

Can you make the bot automatically accept applications as a friend?
P.S. sorry for bad English.

**Comment by Impact123** [comment]
> Can you make the bot automatically accept applications as a friend? 

It already does that.

**Comment by SHAREN** [comment]
I am a member of the group and delete to check bot from friends and then added again, but it does not automatically confirm request.

**Comment by Impact123** [comment]
It should accept upon sending a message. This is not really the place to discuss this though. You can [add me on steam](http://steamcommunity.com/profiles/76561198026608681/) if you want to.

**Comment by Dovahkiin-Warrior** [comment]
I added you, I have a suggestion. Make the plugin check the players once every hour and send it to online admins.
