### ISSUE TITLE
Sound Changable 

### ISSUE THREAD

**Issue by shuksieno123** [Impact123/CallAdmin#19]
Hello,

Are u Able to change the sound for us :) ?

**Comment by Impact123** [comment]
Do you mean the sound of [The CallAdmin Client](https://github.com/popoklopsi/CallAdmin-Client)? It has its own issue tracker.

**Comment by shuksieno123** [comment]
Yes i mean the Sound of the Calladmin Client are you able to change the sounds there or too switch between 1 or 2 sounds i know it makes the file bigger but some admins are fucked up of this sound because there some free caller on the server we mute them so they are blacklisted but if there more people they will abuse so it was only a question if you were able to do it :)

**Comment by Impact123** [comment]
I,m sure it's possible, but the client is developed entirely by popoklopsi in its own project (see link i posted earlier).

**Comment by shuksieno123** [comment]
Well, I see sorry than i will ask there if hes able to change it but thanks for reply so early: )
