### ISSUE TITLE
Desktop Client

### ISSUE THREAD

**Issue by LubricantJam** [Impact123/CallAdmin#23]
Hey,

It seems whenever I open the desktop client, around 10 seconds or so it says the application is no longer responding and closes. 

Are you aware of this?

**Comment by LubricantJam** [comment]
![Image](http://i.imgur.com/L8D9xto.png)

**Comment by Impact123** [comment]
No, so far there were no reports in [CallAdmin's forum thread](https://forums.alliedmods.net/showthread.php?t=213670) about it. The client has [its own repo](https://github.com/popoklopsi/CallAdmin-Client) linked in [the readme](https://github.com/Impact123/CallAdmin/blob/development/README.md). Popoklopsi might be able to help you find out the cause of it.

**Comment by LubricantJam** [comment]
Alrighty, does he actively check because it seems he hasn't replied to existing issues. I'll re-create this one there.

**Comment by Impact123** [comment]
He's often very busy but I hope so.
