### ISSUE TITLE
[TeamSpeak 3] Add idea

### ISSUE THREAD

**Issue by Had3s99** [Impact123/CallAdmin#29]
Hello,

I want to know if it will be possible to add into ts3 module, sending a message in function of id groups of the users ?

Thank you,

Have a good day.

**Comment by Impact123** [comment]
You mean sending to all users inside of a group? I wanted to add this for a while but i don't use teamspeak anymore and the steam module seems to be the favorite of most users so it got the most attention. There would have to be an easy way to configure this and i might be on board with adding it.

**Edit**: I've looked into this some more and right now this is not worth it, I'm sorry.
