### ISSUE TITLE
[redirect.smx] A2S error 'TimeOut' while refreshing 217.11.249.93:27206 infos

### ISSUE THREAD

**Issue by Czechball** [Impact123/CallAdmin#32]
Hello, I'm getting this error ``[redirect.smx] A2S error 'TimeOut' while refreshing 217.11.249.93:27206 infos`` in console and I'm unable to list any server information. I checked that the IPs are correct. What could be wrong? I'm currently using this on 4 servers and it's not working on any of them.

**Comment by Impact123** [comment]
I have no idea where you got that plugin from, but CallAdmin has no official `redirect.smx` module. Please ask the author of it for support.

**Comment by geominorai** [comment]
I believe that message is from a server redirect plugin: https://forums.alliedmods.net/showthread.php?t=255675

**Comment by Czechball** [comment]
Omg I'm sorry... I had many GitHub tabs open and picked the wrong one... CallAdmin is working perfectly fine for me.
Closing.
