### ISSUE TITLE
Help Call admin+discord

### ISSUE THREAD

**Issue by chulicoxd** [Impact123/CallAdmin#36]
Hello very good that I have a question, I just want to have the call admin + discord. as I don't see a guide on how to configure the discord plugin. I would only have to place those two complements or would I have to add any more? that's why my question is a rookie and I really am in matters of complements, I hope your answer thanks.

**Comment by Impact123** [comment]
This is a bug tracker. Please ask your question in [the forums](https://forums.alliedmods.net/showthread.php?t=213670). The discord module is unsupported and i can't give you support for it. To run it you need to install https://forums.alliedmods.net/showthread.php?t=292663.
