### ISSUE TITLE
new dev version give me errors (Steam Module)

### ISSUE THREAD

**Issue by freakexeuLow** [Impact123/CallAdmin#38]
Hey Impact, 

danke erstmal für das Update und ich habe seit dem neuen Release ein Problem mit dem Calladmin Steam Modul. Es zeigt mir diesen Fehler hier an.
```
L 03/28/2020 - 12:21:20: SourceMod error session started
L 03/28/2020 - 12:21:20: Info (map "de_mirage") (file "/home/user2-9/server/csgo/csgo/addons/sourcemod/logs/errors_20200328.log")
L 03/28/2020 - 12:21:20: [SM] Exception reported: Option with value '4' is invalid!
L 03/28/2020 - 12:21:20: [SM] Blaming: calladmin_steam.smx
L 03/28/2020 - 12:21:20: [SM] Call stack trace:
L 03/28/2020 - 12:21:20: [SM]   [0] MessageBot_SetOption
L 03/28/2020 - 12:21:20: [SM]   [1] Line 119, gameserver/calladmin_steam.sp::OnConfigsExecuted
L 03/28/2020 - 12:25:52: Error log file session closed.
L 03/28/2020 - 12:25:53: SourceMod error session started
L 03/28/2020 - 12:25:53: Info (map "de_mirage") (file "/home/user2-9/server/csgo/csgo/addons/sourcemod/logs/errors_20200328.log")
L 03/28/2020 - 12:25:53: [SM] Exception reported: Option with value '4' is invalid!
L 03/28/2020 - 12:25:53: [SM] Blaming: calladmin_steam.smx
L 03/28/2020 - 12:25:53: [SM] Call stack trace:
L 03/28/2020 - 12:25:53: [SM]   [0] MessageBot_SetOption
L 03/28/2020 - 12:25:53: [SM]   [1] Line 119, gameserver/calladmin_steam.sp::OnConfigsExecuted
```

**Comment by Impact123** [comment]
Deine MessageBot extension ist zu alt. Du kannst die neuste Version hier finden: https://github.com/dordnung/MessageBot/releases
Anleitung hier: https://github.com/dordnung/MessageBot/blob/master/README.md#installation

Your MessageBot extension ist too old. You can find the newest version here: https://github.com/dordnung/MessageBot/releases
Instructions here: https://github.com/dordnung/MessageBot/blob/master/README.md#installation

**Comment by freakexeuLow** [comment]
> 
> 
> Deine MessageBot extension ist zu alt. Du kannst die neuste Version hier finden: https://github.com/dordnung/MessageBot/releases
> Anleitung hier: https://github.com/dordnung/MessageBot/blob/master/README.md#installation
> 
> Your MessageBot extension ist too old. You can find the newest version here: https://github.com/dordnung/MessageBot/releases
> Instructions here: https://github.com/dordnung/MessageBot/blob/master/README.md#installation

Danke dir Impact, hatte wirklich noch die 3.0 Version drauf, funktioniert alles nun so wie es soll und schönes Wochenende gewünscht :3
