### ISSUE TITLE
[MySQL module] CallAdmin not working

### ISSUE THREAD

**Issue by KarmaDeb** [Impact123/CallAdmin#39]
Hi, I'm having troubles with calladmin mysql module, when a player types /calladmin and reports someone, this report isn't saved in the mysql, causing I won't receive an alert in the desktop client

**Comment by Impact123** [comment]
Please use the forums for issues like this, this is a bug tracker.
Take a look at [Verifying installation](https://github.com/Impact123/CallAdmin/wiki/Verify-Installation) and [Getting help](https://github.com/Impact123/CallAdmin/wiki/Getting-Help). I recommend you post your logs in the forum thread.
