### ISSUE TITLE
[Steam bot] Steam bot module is causing a server crash

### ISSUE THREAD

**Issue by KarmaDeb** [Impact123/CallAdmin#40]
There's no log, I've already read troubleshooting and nothing found, the server crash after the bot sends the steam message
latest sourcemod version, running on linux/Ubuntu 16.0 with 1028MB

**Comment by Impact123** [comment]
[MessageBot has its own bug tracker and repository here](https://github.com/dordnung/MessageBot). I' recommend installing [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703).
