### ISSUE TITLE
Rss-Feed

### ISSUE THREAD

**Issue by Kammi61871** [Impact123/CallAdmin#43]
I have some Problems with the rss feed everytime when i call the feed it will download rss.php. On my Forum Xenforo2 the rss works without any Problems.
PHP Version = 7.2.34-8+ubuntu20.04.1+deb.sury.org+1

**Comment by Impact123** [comment]
Sounds like a server problem where the php isn't executed but downloaded instead. I'd suggest searching for `php file is downloaded`. Not sure how i can help fixing this
