### ISSUE TITLE
Suggestion: Add target immunity for admins

### ISSUE THREAD

**Issue by Rugal-Servidores** [Impact123/CallAdmin#44]
It would be interesting to add immunity for administrators, I mean, so that their names are not displayed in the report players menu, this is useful so that players do not know that there are administrators on the server (if admins are invisible in spectator mode, which is mine case.)

**Comment by Impact123** [comment]
Thanks for the suggestion. I wrote a module which does this a while ago and published it here: <https://forums.alliedmods.net/showthread.php?p=2668719#post2668719>
[I also published it into the `misc` folder now](https://github.com/Impact123/CallAdmin/commit/66ceac035af09bee61838344bbfdcf332130ab0b).
