### ISSUE TITLE
I do not receive messages when someone calls for admin

### ISSUE THREAD

**Issue by walidbouachir** [Impact123/CallAdmin#45]
Hello,
I have my plugin setup as follow:
in calladmin_steam_groupidlist.cfg file:
// List of group names (custom group name), separated by a new line
// So for example if your community link is: http://steamcommunity.com/groups/Valve then write in a new line: Valve
// YourGroupName
adminsbynox

in calladmin_steam_steamidlist.cfg file:
// List of steamids or communityids, seperated by a new line
// STEAM_0:0:1
// 76561197960265730
STEAM_0:1:544522056
STEAM_0:0:571660736

I'm not sure if I missed something here, I have extracted both the Call Admin Plugin .zip & the Steam Module .zip files into my server, but in the sourcemod logs folder I get the following in a logged text file:

L 05/06/2021 - 22:48:33: [CallAdmin: Steam module] Failed to send steam message: (result: 1 [No recipients were setup prior to sending a message] | error: No receiver was configurated)
L 05/07/2021 - 00:27:35: [CallAdmin: Steam module] Failed to send steam message: (result: 1 [No recipients were setup prior to sending a message] | error: No receiver was configurated)

I don't get the message to my steam chat if that's what the plugin does, I have a running 24/7 VPS which has steam installed in it (it has admin #1 logged in to his steam there, and I'm the second one on my PC which is not running 24/7) so that means I have total 2 admins on my server. Maybe I missed something here?

With much thanks!

**Comment by Impact123** [comment]
Try to to [reload the config](https://github.com/Impact123/CallAdmin/wiki/Commands#steam-module). The issue tracker isn't the best place for support. You can chat with me on discord if you want. My handle is `Impact#9229`.

**Comment by walidbouachir** [comment]
> Try to to [reload the config](https://github.com/Impact123/CallAdmin/wiki/Commands#steam-module). The issue tracker isn't the best place for support. You can chat with me on discord if you want. My handle is `Impact#9229`.

Added you there
