### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by umbr1X** [Impact123/CallAdmin#49]
L 04/09/2023 - 16:51:33: [SM] Exception reported: Language phrase "CallAdmin_RecentlyReported" not found (arg 7)
L 04/09/2023 - 16:51:33: [SM] Blaming: calladmin.smx
L 04/09/2023 - 16:51:33: [SM] Call stack trace:
L 04/09/2023 - 16:51:33: [SM]   [0] Format
L 04/09/2023 - 16:51:33: [SM]   [1] Line 1145, gameserver/scripting/calladmin.sp::ShowClientSelectMenu
L 04/09/2023 - 16:51:33: [SM]   [2] Line 797, gameserver/scripting/calladmin.sp::Command_Call

**Comment by Impact123** [comment]
You might have a development release installed but not the development phrases that go with it. Make sure you installed the recent `calladmin.phrases.txt` into the `translations` folder. I can't tell you more without [more information](https://github.com/Impact123/CallAdmin/wiki/Getting-Help)

**Comment by Impact123** [comment]
Some feedback would have been nice but glad you solved it.
